### ISSUE TITLE
/. (秒数指定なし)でピリオドマッチを開始したとき、/jp offを推奨するメッセージが表示されず同じメッセージが2回表示されている。

### ISSUE THREAD

**Issue by expacraft** [jaoafa/PeriodMatch2#2]
![image](https://user-images.githubusercontent.com/75877469/116768562-63113d80-aa72-11eb-87c8-e4c9101b30cc.png)

![image](https://user-images.githubusercontent.com/75877469/116768601-a9669c80-aa72-11eb-98bc-b2e48ae703a6.png)

**Comment by book000** [comment]
めも: https://github.com/jaoafa/PeriodMatch2/blob/157f5d63e264229c56cb6464b02855d3f32c3744/src/main/java/com/jaoafa/periodmatch2/command/Period.java#L60
