### ISSUE TITLE
ピリオドマッチが終わった後何秒か経ったらしゃべれるようにしてほしい。

### ISSUE THREAD

**Issue by kinoko2k** [jaoafa/PeriodMatch2#26]
### 対象の機能

ピリオドマッチ

### 強化・改善の内容

ピリオドマッチが終わった後、クライアントとサーバのラグかなんかで終わった後も.が送信され続けてSPAMになる場合があるので、しゃべれるのを阻止したほうがよさそうと思いました。

**Comment by book000** [comment]
終了後数秒間発言できない、というのはいくつかの観点で問題があるように思えます。

- サーバ負荷による連投: 鯖負荷が高い場合、スケジューリングシステムにも影響が及ぼされ、チャットの処理も遅延するようになります。もし機能を追加した場合、「普通のメッセージ」が拒否される危険性と、スケジューリングシステムが遅延し制限時間が外れた後でチャットが送信される場合があります。したがって、機能についての実質的なメリットがなくなる可能性があります。
  クライアント負荷の場合、プラグインはサーバ側の処理で動くので機能通りに動作することが想定されます。
- UX: マッチ時間外に数秒間発言できないのは普通にストレスになりそうな気がします。かといって短すぎると機能としての意味がなくなるので、うーんって感じです

そもそも、[コミュニティ方針的に「悪気のないスパム (ピリオド連投なんていい例だと思うのですが)」は許容される傾向](https://jaoafa.com/server/guidelines/communications/)にあり、運営としては「許容されるべき」だと思っています。わざわざプラグイン機能としてこれを制限する必要性を正直あまり感じていないのですが、いかがでしょうか。

**Comment by kinoko2k** [comment]
ですが、あまりチャットが流れすぎるとピリオドだった場合も邪魔だと思いますが…

**Comment by kohonayoshi** [comment]
マジレスすいませんが、そんなに最近みんなピリオドマッチしてないんで大丈夫です。

**Comment by kinoko2k** [comment]
じゃあ閉じたほうがいいでしょうか
